# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33290db6bb7fc7dd12d520b96a4f515e3b269405b8f087cf56d21493a32ab0d4f8349c74486e6496b30e2b12363ddc616999112e98f68d48ef135e2541a62e7e

test:
  secret_key_base: ec0ba1bb1b6b75f6c1b1092b85d6cf839e1daf5ded0e408edbec3584b198d81d313b817c3dc622bcd76a8424ea5261d01e14781a53e3ec996f4e4a021e014b8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
